In [3]:
import tensorflow as tf

2024-08-30 18:26:41.782061: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.


In [4]:
tf.__version__

'2.16.1'

## Basics of Tensor Operations

In [3]:
a = tf.constant([[1, 2],[3, 4]], dtype = tf.float32)
b = tf.constant([[5, 6],[7, 8]], dtype = tf.float32)

In [4]:
print(a)

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)


In [5]:
print(b)

tf.Tensor(
[[5. 6.]
 [7. 8.]], shape=(2, 2), dtype=float32)


## Arithematic Operations

- tf.add()<br>
- tf.subtract()<br>
- tf.multiply()<br>
- tf.divide()

In [6]:
tf.add(a, b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 6.,  8.],
       [10., 12.]], dtype=float32)>

In [7]:
tf.subtract(a, b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-4., -4.],
       [-4., -4.]], dtype=float32)>

In [8]:
tf.multiply(a, b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 5., 12.],
       [21., 32.]], dtype=float32)>

In [9]:
tf.divide(a, b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[0.2       , 0.33333334],
       [0.42857143, 0.5       ]], dtype=float32)>

## Mathematical Functions

- tf.square()<br>
- tf.sqrt()<br>
- tf.exp()<br>
- tf.math.log()<br>

In [33]:
tf.square(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.,  4.],
       [ 9., 16.]], dtype=float32)>

In [34]:
tf.sqrt(b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[2.236068 , 2.4494898],
       [2.6457512, 2.828427 ]], dtype=float32)>

In [35]:
tf.math.log(b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[1.609438 , 1.7917595],
       [1.9459101, 2.0794415]], dtype=float32)>

In [36]:
tf.exp(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 2.7182817,  7.389056 ],
       [20.085537 , 54.59815  ]], dtype=float32)>

## Reduction Operations

- tf.reduce_mean()<br>
- tf.reduce_sum()<br>
- tf.reduce_max() <br>
- tf.reduce_min()

In [39]:
c = tf.constant([[1,2,3,4,5],[6,7,8,9,10],[5,7,8,1,8],[7,4,1,8,9]])
print(c)

tf.Tensor(
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 5  7  8  1  8]
 [ 7  4  1  8  9]], shape=(4, 5), dtype=int32)


In [41]:
tf.reduce_mean(c, axis = 0)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([4, 5, 5, 5, 8], dtype=int32)>

In [42]:
tf.reduce_sum(c, axis  = 0)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([19, 20, 20, 22, 32], dtype=int32)>

In [43]:
tf.reduce_max(c, axis = 0)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 7,  7,  8,  9, 10], dtype=int32)>

In [44]:
tf.reduce_min(c, axis = 0)

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([1, 2, 1, 1, 5], dtype=int32)>

##  Matrix Multiplications

In [46]:
d =  tf.constant([[5,8,1,2],[7,9,10,11]])
d

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 5,  8,  1,  2],
       [ 7,  9, 10, 11]], dtype=int32)>

In [47]:
tf.matmul(a, b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[19., 22.],
       [43., 50.]], dtype=float32)>

In [49]:
tf.transpose(d)

<tf.Tensor: shape=(4, 2), dtype=int32, numpy=
array([[ 5,  7],
       [ 8,  9],
       [ 1, 10],
       [ 2, 11]], dtype=int32)>

In [52]:
tf.linalg.inv(a)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-2.0000002 ,  1.0000001 ],
       [ 1.5000001 , -0.50000006]], dtype=float32)>

In [53]:
tf.linalg.inv(b)

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-4.000002 ,  3.0000014],
       [ 3.5000017, -2.5000012]], dtype=float32)>

## Indexing & Slicing

In [55]:
print(d)

tf.Tensor(
[[ 5  8  1  2]
 [ 7  9 10 11]], shape=(2, 4), dtype=int32)


In [56]:
d[0,0]

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [57]:
d[0,2]

<tf.Tensor: shape=(), dtype=int32, numpy=1>

In [60]:
d[1, 3]

<tf.Tensor: shape=(), dtype=int32, numpy=11>

## Broadcasting

In [62]:
print(d)

tf.Tensor(
[[ 5  8  1  2]
 [ 7  9 10 11]], shape=(2, 4), dtype=int32)


In [64]:
e = tf.constant([4,8,1,5])
print(e)

tf.Tensor([4 8 1 5], shape=(4,), dtype=int32)


In [65]:
tf.add(d, e)

<tf.Tensor: shape=(2, 4), dtype=int32, numpy=
array([[ 9, 16,  2,  7],
       [11, 17, 11, 16]], dtype=int32)>

## Variables in TensorFloe

In [12]:
initial_values = tf.random.normal(shape = (6, 7))

variable_tensor = tf.Variable(initial_values)

In [13]:
variable_tensor

<tf.Variable 'Variable:0' shape=(6, 7) dtype=float32, numpy=
array([[-0.5395072 ,  1.2321668 ,  0.40843126,  0.41338095,  0.16773634,
        -0.40036005, -0.05249739],
       [ 1.9597858 ,  0.4069471 , -0.2784195 ,  0.7447466 , -0.13363121,
        -0.39932537,  0.27194655],
       [-1.3706888 ,  0.1979829 ,  0.7772714 ,  0.62979335,  1.0546943 ,
         0.2645205 , -0.09826523],
       [ 0.3331402 ,  0.24735078,  1.8395106 ,  0.31771377, -0.12550296,
        -0.44772667, -1.1808784 ],
       [ 1.6418152 , -0.07594151,  0.28777117,  0.46202505, -0.8885841 ,
         0.27351645, -0.01038177],
       [ 0.21169873, -0.24136752,  0.43973795, -0.9798966 ,  0.98947775,
         0.7469706 ,  0.19179462]], dtype=float32)>

In [17]:
new_values = tf.random.normal(shape = (6, 7))
new_values

<tf.Tensor: shape=(6, 7), dtype=float32, numpy=
array([[ 0.15558913,  0.5384732 ,  0.03259306,  0.6926509 , -0.45386443,
        -2.370869  , -1.4132535 ],
       [-0.20217757, -1.1573515 ,  0.9809316 , -0.577549  ,  0.5732406 ,
        -0.19011126, -1.1170092 ],
       [-0.13428691,  0.29195076, -2.4436715 ,  1.0787627 , -0.6507687 ,
        -0.96080536, -0.40675795],
       [-1.4706616 , -0.93075836,  2.0343356 , -0.17838494, -1.5043135 ,
        -2.1709146 ,  1.2329742 ],
       [ 0.7805299 ,  1.3937447 ,  0.677938  , -0.66967005,  0.73782134,
        -0.4969616 ,  0.90960824],
       [ 0.94206715, -1.332901  ,  0.18206404, -0.8187212 ,  0.92301023,
        -0.1401307 , -0.2755052 ]], dtype=float32)>

In [18]:
variable_tensor.assign(new_values)

<tf.Variable 'UnreadVariable' shape=(6, 7) dtype=float32, numpy=
array([[ 0.15558913,  0.5384732 ,  0.03259306,  0.6926509 , -0.45386443,
        -2.370869  , -1.4132535 ],
       [-0.20217757, -1.1573515 ,  0.9809316 , -0.577549  ,  0.5732406 ,
        -0.19011126, -1.1170092 ],
       [-0.13428691,  0.29195076, -2.4436715 ,  1.0787627 , -0.6507687 ,
        -0.96080536, -0.40675795],
       [-1.4706616 , -0.93075836,  2.0343356 , -0.17838494, -1.5043135 ,
        -2.1709146 ,  1.2329742 ],
       [ 0.7805299 ,  1.3937447 ,  0.677938  , -0.66967005,  0.73782134,
        -0.4969616 ,  0.90960824],
       [ 0.94206715, -1.332901  ,  0.18206404, -0.8187212 ,  0.92301023,
        -0.1401307 , -0.2755052 ]], dtype=float32)>

In [19]:
variable_tensor

<tf.Variable 'Variable:0' shape=(6, 7) dtype=float32, numpy=
array([[ 0.15558913,  0.5384732 ,  0.03259306,  0.6926509 , -0.45386443,
        -2.370869  , -1.4132535 ],
       [-0.20217757, -1.1573515 ,  0.9809316 , -0.577549  ,  0.5732406 ,
        -0.19011126, -1.1170092 ],
       [-0.13428691,  0.29195076, -2.4436715 ,  1.0787627 , -0.6507687 ,
        -0.96080536, -0.40675795],
       [-1.4706616 , -0.93075836,  2.0343356 , -0.17838494, -1.5043135 ,
        -2.1709146 ,  1.2329742 ],
       [ 0.7805299 ,  1.3937447 ,  0.677938  , -0.66967005,  0.73782134,
        -0.4969616 ,  0.90960824],
       [ 0.94206715, -1.332901  ,  0.18206404, -0.8187212 ,  0.92301023,
        -0.1401307 , -0.2755052 ]], dtype=float32)>

In [20]:
weight = tf.Variable(3)

In [21]:
weight

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=3>

In [22]:
tf.Variable(tf.random.normal(shape = (5, 6)))

<tf.Variable 'Variable:0' shape=(5, 6) dtype=float32, numpy=
array([[-0.20981984,  0.46899185, -0.4642803 ,  0.6854699 , -0.8221248 ,
        -0.8806995 ],
       [ 0.77303034,  0.44080666, -0.3428576 ,  0.5066898 , -2.5691123 ,
        -1.0802735 ],
       [ 0.97148365,  0.6410805 ,  1.1523584 ,  0.6391375 ,  1.278737  ,
        -0.43249276],
       [-1.1467807 , -1.0875322 , -0.9875282 ,  0.4682523 ,  0.20904015,
        -0.5785452 ],
       [-1.576418  , -0.42675105,  1.9136455 ,  1.0131806 ,  0.47654918,
        -0.8509015 ]], dtype=float32)>